apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: apps

spec:
  type: LoadBalancer
  selector:
    app: app2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
