apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: monitoringAPPDb
          ports:
            - containerPort: 3306
