apiVersion: apps/v1
kind: deployment 
metadata:
  name: app1
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: drissjabri/app1
          ports: 
            - containerPort: 8090