apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: drissjabri/app1
          ports:
            - containerPort: 8081
          env:
            - name: TEMPO_ENDPOINT
              value: "http://tempo.monitoring:9411"
            - name: LOKI_ENDPOINT
              value: "http://loki.monitoring:3100"