apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081

